# Generated by Django 3.2.16 on 2022-10-07 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('valor_custo', models.FloatField(blank=True, max_length=10, null=True)),
                ('valor_venda', models.FloatField(blank=True, max_length=10, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('code_bar', models.CharField(blank=True, max_length=20, null=True)),
                ('descricao', models.TextField(blank=True, max_length=200, null=True)),
                ('empty', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categoria.category')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.company')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
            },
        ),
    ]
