# Generated by Django 3.2.16 on 2022-10-07 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15)),
                ('detalhes', models.CharField(blank=True, max_length=255, null=True)),
                ('dinheiro', models.BooleanField(default=False)),
                ('pix', models.BooleanField(default=False)),
                ('debito', models.BooleanField(default=False)),
                ('credito', models.BooleanField(default=False)),
                ('obs', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item', models.ManyToManyField(blank=True, to='item.Item')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.store')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
    ]
